### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by barnabaskecskes** [tonchik-tm/pdf-to-html#1]
I'm having an issue when calling the `getHtml()` method. See image below - help would be appreciated. :)

<img width="884" alt="screen shot 2015-09-17 at 23 18 13" src="https://cloud.githubusercontent.com/assets/3535449/9947582/180f3ce2-5d93-11e5-9990-7a6151ffe7a0.png">

**Comment by KenFlip** [comment]
Hi,

I know its a year afterwards but im having issues with this, please se below:

`<?php
	// if you are using composer, just use this
	include 'vendor/autoload.php';

	// initiate
	$pdf = new \TonchikTm\PdfToHtml\Pdf(BASE_PATH . 'uploads/pdf/test.pdf', [
	    'pdftohtml_path' => '/usr/bin/pdftohtml',
	    'pdfinfo_path' => '/usr/bin/pdfinfo'
	]);

	// get pdf info
	$pdfInfo = $pdf->getInfo();

	// get count pages
	$countPages = $pdf->countPages();

	// get content from one page
	$contentFirstPage = $pdf->getHtml()->getPage(1);

	// get content from all pages and loop for they
	foreach ($pdf->getHtml()->getAllPages() as $page) {
	    echo $page . '<br/>';
	}
?>`

And this is the output i am getting:

`
Notice: Undefined index: pages in /Users/Tin/Documents/Work/flipswitch-framework/vendor/tonchik-tm/pdf-to-html/src/Pdf.php on line 81

Strict Standards: Only variables should be passed by reference in /Users/Tin/Documents/Work/flipswitch-framework/vendor/tonchik-tm/pdf-to-html/src/Pdf.php on line 178

Notice: Undefined index: pages in /Users/Tin/Documents/Work/flipswitch-framework/vendor/tonchik-tm/pdf-to-html/src/Pdf.php on line 81

Strict Standards: Only variables should be passed by reference in /Users/Tin/Documents/Work/flipswitch-framework/vendor/tonchik-tm/pdf-to-html/src/Pdf.php on line 178

Notice: Undefined index: pages in /Users/Tin/Documents/Work/flipswitch-framework/vendor/tonchik-tm/pdf-to-html/src/Pdf.php on line 81`

This is really really urgent as I need to get this done by today, please advise asap 👍

**Comment by daviddebeer** [comment]
Has anyone found a solution to this yet?

**Comment by tonchik-tm** [comment]
Done

**Comment by atif-kht** [comment]
I am still getting this issue and no html is generated:

Undefined index: pages in F:\wamp\www\pdf2htmltonchik\vendor\tonchik-tm\pdf-to-html\src\Pdf.php on line 81
